# Generated by Django 3.1.3 on 2021-01-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='date',
        ),
    ]
