# Generated by Django 3.1.3 on 2021-01-21 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_grocery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
